### ISSUE TITLE
Overlapping widgets on Windows with screen height smaller than 800 pixels

### ISSUE THREAD

**Issue by NemoNick** [MaurizioB/Bigglesworth#2]
Hi !
Small issues with the GUI, lower part.
Screen capture of GUI below (Windows 7 ; Screen res.: 1366x768)
Thanks for the great work !
Greetings,
Nic M

![bigglesworth 0 9 7 gui issues](https://cloud.githubusercontent.com/assets/28223105/25564885/e4ea6462-2dbc-11e7-8454-ed4f39821fb8.png)

**Comment by MaurizioB** [comment]
Hello, @NemoNick, and thank you.
Unfortunally, Bigglesworth (at least, right now) only supports screen resolutions with at least 1280 for width and 800 for height, and that's excluding system panels (such as the taskbar in Windows); also, on Windows there's an issue regarding the font size, which makes all fonts slightly bigger than they are on Linux or OSX. That's why you have all those widgets garbled and overlapped. As a reference, my Editor window has a size of 1247x789, including window decoration (the title bar).
I'm trying to find solutions for this kind of issues: as you can see the display on top uses too much space and also has empty margins (which doesn't happen on Linux) and this is because the Modulation Matrix requires too much height due to the font size issue I mentioned before.
Since I also have problems with modern system which use High DPI screens, I'm evaluating the possibility to set custom sizes for both widgets (dials) and fonts, which *might* solve the problem, at least partially.
At this time, there's not much you can do about it, since, as I can see, you're already using all the available space. Sorry about that.
I'll mark this Issue as solved as soon as I find a solution.
Thank you.

**Comment by NemoNick** [comment]
Hi again Maurizio,
thanks for the fast answer 
I 'll try Bigglesworth on another computer as I can't go further than 1366x768.
Everything works smooth otherwise so I'll use it as is and keep my eyes on the updates !
Cheers
Nic M.

**Comment by MaurizioB** [comment]
You are welcome. Anyway, there is a simple (automatic) version check on start up, which will alert you whenever a new version becomes available. I'm working on other features right now, also because this size issues take a lot of time and testing, but I'm planning on solving them as soon as possible.
Let me know if you still have problems on higher resolution screens, though!
Cheers

**Comment by NemoNick** [comment]
Will do !
N.

**Comment by gatesphere** [comment]
I'd like to +1 this and bring it back to attention -- I too am stuck to 1366x786 resolution, though I'm running on Arch Linux.  Unfortunately, the editor UI is basically unusable for me since a large chunk of it is off the edge of my screen.

I see there hasn't been a commit in about a year -- and that's cool if you've moved on to greener pastures.  I just thought I'd poke at this issue and see if there's been any movement.  (I might fork it and see if I can make something work on my own, though I don't really know Qt enough to really give it a shot...)

**Comment by MaurizioB** [comment]
Hi @gatesphere, and thank you for your message.
I'm sorry I didn't push anything in the latest months, I was very busy and, after some other work on other projects, when I went back to Bigglesworth's code I realized that it's a mess (experience, huh?) ;-) Actually, in the last 3 months I've been working hard on an almost complete rewrite, since lots of things that needed to be fixed were so poorly written that fixing them would have been a major pain in the...
This pushed the long waited new release back by some months, but the wait should be repaid. For example, with the new graphics it takes about 1092x700 on my screen, including the title bar, while the last release was 1278x860. Also, it now supports themeing and font sizing, which will eventually grant even more space saving. I'm not able to tell you when it will be released, possibly within a month. If you use facebook, you can like the official page, where I'm posting updates about the project status: https://www.facebook.com/bigglesworthapp/

Cheers!

**Comment by MaurizioB** [comment]
Closing as the latest [dev] versions solve the main issue by using new widgets and better layout management.
Some further optimization will still be done in the future, though.
